### ISSUE TITLE
Documentation upgrade

### ISSUE THREAD

**Issue by daniellivingston** [amanzi/amanzi#388]
Documentation, particularly the User Guide and top-level web view of Amanzi, needs to be upgraded to have a more modern feel and be integrated into standard builds and TravisCI.

- [x] User guide (and all Python files) need to be upgraded to Python 3.x (See #365, #394 )
- [x] User guide style needs upgrading (`livingston/docs_new_theme`)
- [ ] Plots in the User Guide need to be cleaned up (See #398)
- [ ] All [Verification tickets](https://github.com/amanzi/amanzi/issues/assigned/johnportiz14) need to be verified + closed
- [x] Documentation and tests from amanzi-0.87 need to be merged into master (done: #387)
- [ ] Hantush test needs fixing
- [ ] User guide needs to be deployed to `gh-pages` via TravisCI
- [x] User guide needs to be built as part of bootstrap

**Comment by daniellivingston** [comment]
Regarding documentation via CI, it's trivial in Travis.

See an example on how we've done it for FEHM (https://github.com/lanl/FEHM/blob/master/.travis.yml#L41):
```
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/docs/html
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  keep_history: false
  verbose: true
  on:
    branch: master
```

It requires three steps:

1. Documentation is built during `script` or `after_success` stage
2. The path variable `local_dir` points to the root directory of the generated HTML files (i.e. for Amanzi: `doc/user_guide/_build/html`)
3. `GITHUB_TOKEN` is a private key generated on GitHub and pasted into TravisCI repo settings

Then, on every push, compiled documentation is pushed to `target_branch`. Commit history on this branch is removed.

**Comment by jd-moulton** [comment]
Last commit (280ba4f57) closed #394.  Not sure why it didn't close this issues as claimed, but good that it didn't since it was a typo.

**Comment by daniellivingston** [comment]
@jd-moulton @lipnikov The missing schematic files have been added in 19048886ebcd01a7521bfe77d0c23c620d9e56cb
