### ISSUE TITLE
TPL Updates for version 0.98.7

### ISSUE THREAD

**Issue by jd-moulton** [amanzi/amanzi#742]
We need to aggregate updates for TPLs coming in from PRs to avoid users having to rebuild the tpls too often.  We may integrate other minor updates to some libraries as well.   The current PRs are:

- [x] update ExprTk package (#734)
- [ ] patch netcdf-fortran cmake (#735)
- [ ] fix confusing naming (#736)

In addition, to prepare for the work on gas diffusion we need to update a geochemistry related libraries

- [x] alquimia v1.0.10
- [x] PetSc v3.18.5
- [x] Sowing that goes with PetSc
- [x] PFLOTRAN  v4.0.1

And we need to restore the ability to build either CrunchFlow or PFLOTRAN, but not require both.
These updates bring us closer to being in sync with xSDK 0.8.0.  We may consider updating 

- [ ] Hypre v2.6.0
- [ ] Trilinos 14.0.0

as well.

**Comment by jd-moulton** [comment]
These updates shifted to TPLs version 0.98.8.
