### ISSUE TITLE
Checklist for Amanzi 1.5 release

### ISSUE THREAD

**Issue by jd-moulton** [amanzi/amanzi#840]
This in umbrella ticket intended to capture the updates and tests we make after the amanzi-1.5 branch was cut, and with features on this branch considered frozen.  

- [x] Update any static version information
- [x] Test TPL builds across systems
- [x] Test Amanzi builds and run tests across systems
- [x] Test optional use of PFLOTRAN or CrunchFlow as geochemistry engines
- [x] Build documentation and update
- [x] Update supported build tools (cmake, compilers, mpi)
- [x] Spec versioning, and spec description version in User Guide
