### ISSUE TITLE
Containerization umbrella issue

### ISSUE THREAD

**Issue by rfiorella** [amanzi/amanzi#853]
This ticket collects several other issues related to containerization (#842 , #814 , #769 , #762 , #761 , #760 ).

These tickets point out at least three capabilities that could use some standardization:
- [ ] multiarch builds for the TPL containers, given increasing use of arm64 
- [ ] multiarch builds for the Amanzi and ATS containers, given increasing use of arm64 (green below)
- [ ] Containers with some enhanced capabilities (e.g., jupyter lab) (blue below)

A fourth issue seems relevant and potentially useful for CI - using build artifacts in GitHub for TPLs and testing on macOS in addition to ubuntu:jammy (red below)

The latter two cases are overkill for CI, but might be good to build for pull requests and/or releases.
I've tried to outline a GitHub actions workflow that might meet these needs below:
<img width="886" alt="Drawing8" src="https://github.com/user-attachments/assets/6e3cab75-b9a4-4ad8-9261-ba161eeeab79">

Feedback welcome. 
Any use cases I'm missing? @jd-moulton @ecoon

**Comment by rfiorella** [comment]
Github actions expected to provide ARM runners in free tier by the end of the year: https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/
